### ISSUE TITLE
Tracking issue for num-bigint 0.3

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-bigint#128]
- [x] Update MSRV to 1.31, needed to deal with rand's use of package renaming
  - [x] #130: Convert to 2018 edition too
- [x] #62: Finish support for 64-bit `BigDigit`
- [x] #101: Enable `no_std` with the alloc crate (MSRV 1.36)
- [x] ~~#105: Add comparisons with primitive integers (affecting type inference)~~
  - Reverted in #151, as it broke a lot of integer type inference.
- [x] #106: Implement `Pow` by value (affecting calls that currently use references)
- [x] #110: Update to rand 0.7 (MSRV 1.32) and quickcheck 0.9 (MSRV 1.34)
- ~~Reconsider `{Div,Rem}::Output` with primitives to match the smaller type (related to #88)~~
  - Postponing.

Other PRs and issues may be included too, but these are the ones that impact compatibility.
